#!/bin/bash

while test $# -gt 0; do
        case "$1" in
                -h|--help)
                        echo "SpotifyThemer - Customize the theme of spotify for linux"
                        echo " "
                        echo "spotify_themer [options] [COLOR]"
                        echo " "
                        echo "options:"
                        echo "-h, --help                show brief help"
                        echo "-i, icons                 create new icons with COLOR"
                        exit 0
                        ;;
                -i)
                        shift
                        if test $# -gt 0; then
                                export COLOR=$1
                        else
                                echo "no process specified"
                                exit 1
                        fi
                        shift
                        ;;
                icons*)
                        export PROCESS=`echo $1 | sed -e 's/^[^=]*=//g'`
                        shift
                        ;;
                *)
                        break
                        ;;
        esac
done
